import React, { useState } from 'react';
import { X, Download, Copy, Check, FileCode, Package } from 'lucide-react';
import { FlowcraftNode, FlowcraftEdge } from '@nodeframe/types';
import { GitHubActionsGenerator } from '../generators/GitHubActionsGenerator';
import { GitLabCIGenerator } from '../generators/GitLabCIGenerator';
import { JenkinsfileGenerator } from '../generators/JenkinsfileGenerator';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface CodeExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    nodes: FlowcraftNode[];
    edges: FlowcraftEdge[];
}

type Platform = 'github' | 'gitlab' | 'jenkins';

export const CodeExportModal: React.FC<CodeExportModalProps> = ({ isOpen, onClose, nodes, edges }) => {
    const [selectedPlatform, setSelectedPlatform] = useState<Platform>('github');
    const [copied, setCopied] = useState(false);

    if (!isOpen) return null;

    const generateCode = (platform: Platform): string => {
        switch (platform) {
            case 'github':
                return new GitHubActionsGenerator(nodes, edges).generate();
            case 'gitlab':
                return new GitLabCIGenerator(nodes, edges).generate();
            case 'jenkins':
                return new JenkinsfileGenerator(nodes, edges).generate();
        }
    };

    const code = generateCode(selectedPlatform);

    const getFileName = (platform: Platform): string => {
        switch (platform) {
            case 'github':
                return '.github/workflows/ci.yml';
            case 'gitlab':
                return '.gitlab-ci.yml';
            case 'jenkins':
                return 'Jenkinsfile';
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(code);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
        saveAs(blob, getFileName(selectedPlatform).split('/').pop() || 'pipeline.yml');
    };

    const handleExportAll = async () => {
        try {
            console.log('Starting multi-platform export...');
            const zip = new JSZip();

            // Add all platform configs
            const githubCode = new GitHubActionsGenerator(nodes, edges).generate();
            const gitlabCode = new GitLabCIGenerator(nodes, edges).generate();
            const jenkinsCode = new JenkinsfileGenerator(nodes, edges).generate();

            zip.file('.github/workflows/ci.yml', githubCode);
            zip.file('.gitlab-ci.yml', gitlabCode);
            zip.file('Jenkinsfile', jenkinsCode);

            // Add README
            const readme = `# CI/CD Pipeline Configuration

This package contains pipeline configurations for multiple platforms:

## GitHub Actions
- File: \`.github/workflows/ci.yml\`
- Usage: Copy to your repository root

## GitLab CI
- File: \`.gitlab-ci.yml\`
- Usage: Copy to your repository root

## Jenkins
- File: \`Jenkinsfile\`
- Usage: Copy to your repository root or configure in Jenkins

## Generated by NodeFrame CI/CD Builder
`;

            zip.file('README.md', readme);

            console.log('Generating ZIP blob...');
            // Generate and download
            const content = await zip.generateAsync({ type: 'blob' });
            console.log('Triggering download...');
            saveAs(content, 'cicd-pipeline-configs.zip');
            console.log('Export successful!');
        } catch (error) {
            console.error('Export failed:', error);
            alert('Failed to generate export. Check console for details.');
        }
    };

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] flex flex-col">
                {/* Header */}
                <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                            <FileCode className="w-5 h-5 text-white" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-gray-900">Export Pipeline Code</h2>
                            <p className="text-sm text-gray-500">Production-ready CI/CD configurations</p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                    >
                        <X size={20} className="text-gray-500" />
                    </button>
                </div>

                {/* Platform Selector */}
                <div className="px-6 py-4 border-b border-gray-200">
                    <div className="flex gap-2">
                        <button
                            onClick={() => setSelectedPlatform('github')}
                            className={`px-4 py-2 rounded-lg font-medium transition-all ${selectedPlatform === 'github'
                                ? 'bg-gray-900 text-white shadow-md'
                                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                                }`}
                        >
                            GitHub Actions
                        </button>
                        <button
                            onClick={() => setSelectedPlatform('gitlab')}
                            className={`px-4 py-2 rounded-lg font-medium transition-all ${selectedPlatform === 'gitlab'
                                ? 'bg-orange-500 text-white shadow-md'
                                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                                }`}
                        >
                            GitLab CI
                        </button>
                        <button
                            onClick={() => setSelectedPlatform('jenkins')}
                            className={`px-4 py-2 rounded-lg font-medium transition-all ${selectedPlatform === 'jenkins'
                                ? 'bg-red-600 text-white shadow-md'
                                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                                }`}
                        >
                            Jenkins
                        </button>
                    </div>
                </div>

                {/* Code Preview */}
                <div className="flex-1 overflow-hidden flex flex-col">
                    <div className="px-6 py-3 bg-gray-50 border-b border-gray-200 flex items-center justify-between">
                        <span className="text-sm font-mono text-gray-600">{getFileName(selectedPlatform)}</span>
                        <div className="flex gap-2">
                            <button
                                onClick={handleCopy}
                                className="flex items-center gap-2 px-3 py-1.5 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-sm font-medium"
                            >
                                {copied ? (
                                    <>
                                        <Check size={16} className="text-green-600" />
                                        <span className="text-green-600">Copied!</span>
                                    </>
                                ) : (
                                    <>
                                        <Copy size={16} className="text-gray-600" />
                                        <span className="text-gray-700">Copy</span>
                                    </>
                                )}
                            </button>
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-2 px-3 py-1.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
                            >
                                <Download size={16} />
                                Download
                            </button>
                        </div>
                    </div>
                    <div className="flex-1 overflow-auto p-6 bg-gray-900">
                        <pre className="text-sm text-gray-100 font-mono leading-relaxed">
                            <code>{code}</code>
                        </pre>
                    </div>
                </div>

                {/* Footer */}
                <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex items-center justify-between">
                    <div className="text-sm text-gray-600">
                        <span className="font-medium">{nodes.length}</span> nodes • <span className="font-medium">{edges.length}</span> connections
                    </div>
                    <button
                        onClick={handleExportAll}
                        className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg hover:from-purple-700 hover:to-blue-700 transition-all shadow-md font-medium"
                    >
                        <Package size={18} />
                        Export All Platforms (ZIP)
                    </button>
                </div>
            </div>
        </div>
    );
};
