import fs from 'fs';
import path from 'path';

const nodeName = process.argv[2];

if (!nodeName) {
    console.error('Please provide a node name (e.g. MyNode)');
    process.exit(1);
}

const template = `import React from 'react';
import { NodeProps } from 'reactflow';
import { Box } from 'lucide-react';
import { CustomNodeData, BaseNode, defineNodeConfig } from '@nodeframe';

export const ${nodeName}Node: React.FC<NodeProps<CustomNodeData>> = (props) => {
    const { data } = props;
    
    return (
        <BaseNode
            {...props}
            title={data.label || '${nodeName}'}
            icon={<Box size={16} />}
            color={data.color || '#3b82f6'}
        />
    );
};

export const config = defineNodeConfig({
    id: '${nodeName.toLowerCase()}',
    type: '${nodeName.toLowerCase()}',
    label: '${nodeName}',
    category: 'Custom',
    color: '#3b82f6',
    icon: <Box size={16} />,
    defaultData: {
        description: 'New node generated by CLI',
        properties: {},
    },
    propertyDefinitions: [],
    generators: {
        github: (node) => ({ name: node.data.label, run: 'echo "node created"' }),
    },
});
`;

const targetPath = path.join(process.cwd(), 'src', 'nodes', `${nodeName}Node.tsx`);

if (fs.existsSync(targetPath)) {
    console.error(`Node ${nodeName} already exists at ${targetPath}`);
    process.exit(1);
}

// Ensure dir exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, template);
console.log(`Successfully created node: ${targetPath}`);
